disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "5 Minutes Tech >> Learn In Just 5 Minutes"


[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  #logo = "img/blowfish_logo_transparent.png"
  logo = "images/logo-bg.png"
  # secondaryLogo = "img/logo11.png"
  description = "Learn In Just Five Minutes (5min.tech)"
  copyright = "© { year } 5 Minutes Tech. All rights reserved."

[params.author]
  name = "Sourish Bhattacharya"
  email = "blog@sourish4c.com"
  image = "images/me.png"
  imageQuality = 100
  headline = "| Developer | Cloud Engineer | Blogger | Tech Enthusiast |"
  bio = "👋 I'm a Developer, Cloud Engineer, Blogger, Tech Enthusiast"
  links = [
    { youtube = "https://youtube.com/@5-mintech" },
    { github = "https://github.com/sourish4c" },
    { linkedin = "https://linkedin.com/in/sourish4c" },
    { x-twitter = "https://x.com/sourish4c" },
  #  { facebook = "https://facebook.com/username" },
    { instagram = "https://instagram.com/sourish4c" },
    { email = "mailto:blog@sourish4c.com" },
  #  { link = "https://link-to-some-website.com/" },
  #  { ko-fi = "https://ko-fi.com/username" }
  ]